server:
  port: 8060
  tomcat:
    max-http-form-post-size: 8192
spring:
  application:
    name: api-img
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ayaka.icu:3306/api-server?useSSL=false&serverTimezone=UTC
    username: api-server
    password: F2AWsanAPNfpLnr3



# 路径
api:
  server: localhost:8060
  img: # 图片相关配置
    path:
      absolute-path: "D:/desktop/img"
      relative-path: "/img"
      is-relative-path: true
    add: # 添加图片时，使用的请求体参数
      auth: "AHRE56FaehDSFG5agheSFE*&ASDKGJ@&56AG4!@%585AEsfdGSDG"
  # ......

